#!/usr/bin/env bash
# script installs nginx and configures nginx to display custmized content
apt-get update -y
apt-get upgrade -y
apt install nginx -y
service restart nginx
echo 'Hello World!' | tee /var/www/html/*
