#!/usr/bin/env bash
# This script installs nginx and configure it to listen on port 80
# And prints "Hello World"

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
