#!/usr/bin/env bash
# script creates a block that configures page redirect
apt-get update -y
apt-get upgrade -y
apt install nginx -y
echo 'Hello World!' | tee /var/www/html/*
sed -i "s/^\tlocation \/ {/\tlocation \/redirect_me {/g" /etc/nginx/sites-available/default
sed -i "/redirect_me/a\\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-available/default
service nginx start
