#!/usr/bin/env bash
# This script Installs nginx webserver so that /redirect_me redirects to another page.

apt-get update
apt-get install nginx -y


echo "Hello World!" > /var/www/html/index.html
new_str="location \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;"
sed -i '/^#/d' /etc/nginx/sites-available/default
sed -i s/"location \/ {"/"${new_str}"/g /etc/nginx/sites-available/default

service nginx restart
