#!/usr/bin/env bash
# This script Installs nginx webserver configures it so that /redirect_me redirects to another page and customizes 404 error.
apt-get update -y
apt-get upgrade -y
apt install nginx -y
echo 'Hello World!' | tee /var/www/html/*
sed -i "s/^\tlocation \/ {/\tlocation \/redirect_me {/g" /etc/nginx/sites-available/default
sed -i "/redirect_me/a\\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "/^\tserver_name/a\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
service nginx start
