#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get install -y haproxy=2.6\*
# enable HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
config="\nfrontend node-http\n\tbind 0.0.0.0:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\toption forwardfor\n\tserver 39977-web-01 3.236.145.90:80 check\n\tserver 39977-web-02 3.85.148.22:80 check\n\n"
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
