#!/usr/bin/env bash
# This script displays all the minutes of the 24 hours
var=0
LIMIT=12
var1=0
LIMIT1=59

while [ $var -le $LIMIT ]
do
	echo -n "Hour: $var
"
	(( var1 = 1 ))
	while [ $var1 -le $LIMIT1 ]
	do
		echo -n "$var1
"
		(( var1++ ))
	done
	(( var++ ))	
done
exit 0
