#!/usr/bin/env bash
# This script gives info about the file school
FILE="./school"

if [ ! -e $FILE ]
then 
	echo -n "school file does not exist
"
fi

if [ -e $FILE ]
then
	echo -n "school file exists
"

if [ ! -s $FILE  ]
then
	echo -n "school file is empty
"
else
	echo -n "school file is not empty
"
fi

if [ -f $FILE ]
then
	echo -n "school is a regular file
"

fi
fi

exit 0
